import Head from 'next/head';
import {
  Courses,
  About,
  Projects,
  Technologies,
  Intro,
  BgAnimation,
} from '../components';
import { Layout } from '../layout/Layout';
import { Section } from '../styles/GlobalComponents';

const Home = () => {
  return (
    <>
      <Head>
        <title>Aleksandra Szczur | Web Developer with React </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Section grid>
          <Intro />
          <BgAnimation />
        </Section>
        <Projects />
        <Technologies />
        <About />
        <Courses />
      </Layout>
    </>
  );
};

export default Home;
